// <auto-generated />
namespace QLNS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Adddisplaynameforproperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adddisplaynameforproperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201811210328075_Add display name for properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
